In [2]:
import pandas as pd
import numpy as np

In [5]:
x = pd.DataFrame([[1,2], [3,4]],
     columns = ['x1', 'x2'])
x

x1  x2
0   1   2
1   3   4

In [6]:
y = pd.DataFrame([[10,20], [30,40]],
     columns = ['y1', 'y2'])
y

y1  y2
0  10  20
1  30  40

In [23]:
x.x1 + 2*x.x2 #test

0     5
1    11
dtype: int64

In [32]:
z = pd.DataFrame()
z['xcol'] = x.x1 + 2*x.x2
z['ycol'] = y.y1 + 4*y.y2
z.loc[2, 'xcol'] = 1 # 문제없음! 
z.loc[2, 'ycol'] = 10
z

xcol   ycol
0   5.0   90.0
1  11.0  190.0
2   1.0   10.0

In [32]:
z = pd.DataFrame()
z['xcol'] = x.x1 + 2*x.x2
z['ycol'] = y.y1 + 4*y.y2
z.loc[2, 'xcol'] = [1,10] # 에러! 
z.loc[2, 'ycol'] = 10
z

xcol   ycol
0   5.0   90.0
1  11.0  190.0
2   1.0   10.0

In [40]:
A = np.array([[1,2], [3,4]])
A, type(A)

(array([[1, 2],
        [3, 4]]), numpy.ndarray)

In [41]:
B = np.array([[10,20], [30,40]])
B, type(B)

(array([[10, 20],
        [30, 40]]), numpy.ndarray)

In [45]:
A[:,1] + B[1,:] # test: A의 두번째열과 B의 두변쩌행의 합

array([32, 44])

In [52]:
np.array([[B[:,1], A[:,0] +   B[:,1]],[B[:,1], A[:,0] +   B[:,1]]]) # test

array([[[20, 40],
        [21, 43]],

       [[20, 40],
        [21, 43]]])

In [51]:
C = np.array([
    [A[:,0] + 2*A[:,1], A[:,0] + 3*A[:,1], 2*A[:,0]],
    [B[:,0] +   B[:,1], B[:,0] +   B[:,1],   B[:,0]]
    ])
C

array([[[ 5, 11],
        [ 7, 15],
        [ 2,  6]],

       [[30, 70],
        [30, 70],
        [10, 30]]])

In [53]:
pd.Panel

pandas.core.panel.Panel

In [56]:
a = pd.DataFrame([[1,2], [3,4]], columns = ['a1', 'a2'])
b = pd.DataFrame([[11,22], [33,44]], columns = ['b1', 'b2'])
print(a)
print(b)

   a1  a2
0   1   2
1   3   4
   b1  b2
0  11  22
1  33  44


In [58]:
a.a1 + 2*a.a2 #test 

0     5
1    11
dtype: int64

In [69]:
c = pd.DataFrame(
    [['a.a1 + 2*a.a2', '3*a.a1 + a.a2'],
    ['b.b1 + b.b2', '2*a.a1 + b.b2']],
    columns = ['col1', 'col2']
)
c

col1           col2
0  a.a1 + 2*a.a2  3*a.a1 + a.a2
1    b.b1 + b.b2  2*a.a1 + b.b2

In [73]:
# 슬슬 꺼내서 써야할 때만 계산하기
c_to_print = 'saved_value = ' + c.loc[0, 'col1']
print("꺼내기 전 명령이 뭔지 확인 -->", c_to_print)
c_to_print = exec(c_to_print) # str을 interpreter에 넘겨서 명령을 계산시키고 saved_value에 저장
print("계산 후 return된 값 확인 -->\n", saved_value, type(saved_value))

꺼내기 전 명령이 뭔지 확인 --> saved_value = a.a1 + 2*a.a2
계산 후 return된 값 확인 -->
 0     5
1    11
dtype: int64 <class 'pandas.core.series.Series'>


In [75]:
np.exp(1)

2.718281828459045

In [82]:
a1 = a.a1
np.mean(-np.log(np.exp(a1) / sum(np.exp(a1))))

1.1269280110429727

In [103]:
A.sum()

10

In [104]:
A

array([[1, 2],
       [3, 4]])

In [110]:
a = A[0]
a

array([1, 2])

In [112]:
A.dot(a)

array([ 5, 11])

In [114]:
A[1][0]

3

In [115]:
np.zeros_like(A)

array([[0, 0],
       [0, 0]])

In [116]:
np.zeros_like(A[:,0])

array([0, 0])

In [119]:
np.zeros(3)

array([0., 0., 0.])

In [120]:
np.exp(2)

7.38905609893065

In [139]:
A = np.random.randn(2,2) * 0.0001
D = np.zeros_like(A)
D[0][0] = 1/10
D

array([[0.1, 0. ],
       [0. , 0. ]])

In [130]:
np.random.seed(1)
np.random.randn(10, 10)

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
        -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038],
       [ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
        -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521],
       [-1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595,
        -0.68372786, -0.12289023, -0.93576943, -0.26788808,  0.53035547],
       [-0.69166075, -0.39675353, -0.6871727 , -0.84520564, -0.67124613,
        -0.0126646 , -1.11731035,  0.2344157 ,  1.65980218,  0.74204416],
       [-0.19183555, -0.88762896, -0.74715829,  1.6924546 ,  0.05080775,
        -0.63699565,  0.19091548,  2.10025514,  0.12015895,  0.61720311],
       [ 0.30017032, -0.35224985, -1.1425182 , -0.34934272, -0.20889423,
         0.58662319,  0.83898341,  0.93110208,  0.28558733,  0.88514116],
       [-0.75439794,  1.25286816,  0.51292982, -0.29809284,  0.48851815,
        -0.07557171,  1.13162939,  1.51981682

In [180]:
a = np.array(range(10))
np.exp(a)/sum(np.exp(a))
b = np.array(range(0, 100, 10))
a.dot(b)

2850

In [182]:
sum(np.zeros(10)*(a))

0.0

In [184]:
ixs = np.random.choice(a, 2, replace=False)
print("ixs", ixs)
b[ixs]

ixs [4 3]


array([40, 30])

In [204]:
np.random.seed(0)
A = np.random.randn(10, 5) * 100
B = A.astype(int)
print(B)
print(np.max(B[0, :]))
print(B[0, :])
print(B[0, :] + np.max(B[0, :]))

[[ 176   40   97  224  186]
 [ -97   95  -15  -10   41]
 [  14  145   76   12   44]
 [  33  149  -20   31  -85]
 [-255   65   86  -74  226]
 [-145    4  -18  153  146]
 [  15   37  -88 -198  -34]
 [  15  123  120  -38  -30]
 [-104 -142 -170  195  -50]
 [ -43 -125   77 -161  -21]]
224
[176  40  97 224 186]
[400 264 321 448 410]


In [209]:
np.argmax(B[0,:])

3

In [212]:
y_a = np.array([3,2,1,3,5])
y_b = np.array([3,2,1,2,5])
sum(y_a == y_b) / len(y_a)

0.8